/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MalzemeSilButon = new javax.swing.JButton();
        TarifSilButon = new javax.swing.JButton();
        TarifDuzenleButon = new javax.swing.JButton();
        MalzemeAratButon = new javax.swing.JButton();
        MalzemeDuzenleButon = new javax.swing.JButton();
        TarifAratButon = new javax.swing.JButton();
        GeriDonButon = new javax.swing.JButton();
        MalzemeEkle = new javax.swing.JButton();
        TarifEkle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENÜ");

        MalzemeSilButon.setText("Malzeme Sil");
        MalzemeSilButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalzemeSilButonActionPerformed(evt);
            }
        });

        TarifSilButon.setText("Tarif Sil");
        TarifSilButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarifSilButonActionPerformed(evt);
            }
        });

        TarifDuzenleButon.setText("Tarif Düzenle");
        TarifDuzenleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarifDuzenleButonActionPerformed(evt);
            }
        });

        MalzemeAratButon.setText("Malzeme Arat");
        MalzemeAratButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalzemeAratButonActionPerformed(evt);
            }
        });

        MalzemeDuzenleButon.setText("Malzeme Düzenle");
        MalzemeDuzenleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalzemeDuzenleButonActionPerformed(evt);
            }
        });

        TarifAratButon.setText("Tarif Arat");
        TarifAratButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarifAratButonActionPerformed(evt);
            }
        });

        GeriDonButon.setText("Geri Dön");
        GeriDonButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeriDonButonActionPerformed(evt);
            }
        });

        MalzemeEkle.setText("Malzeme Ekle");
        MalzemeEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalzemeEkleActionPerformed(evt);
            }
        });

        TarifEkle.setText("Tarif Ekle");
        TarifEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarifEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(GeriDonButon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TarifDuzenleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TarifAratButon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TarifSilButon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TarifEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MalzemeEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MalzemeSilButon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MalzemeDuzenleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MalzemeAratButon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MalzemeEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TarifEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TarifSilButon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MalzemeSilButon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TarifDuzenleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MalzemeDuzenleButon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TarifAratButon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MalzemeAratButon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GeriDonButon)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GeriDonButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriDonButonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_GeriDonButonActionPerformed

    private void TarifEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarifEkleActionPerformed
        // TODO add your handling code here:
        TarifEkle tarifekle = new TarifEkle();
        tarifekle.setVisible(true);
    }//GEN-LAST:event_TarifEkleActionPerformed

    private void MalzemeEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalzemeEkleActionPerformed
        // TODO add your handling code here:
        MalzemeEkle malzemeekle = new MalzemeEkle();
        malzemeekle.setVisible(true);
    }//GEN-LAST:event_MalzemeEkleActionPerformed

    private void TarifSilButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarifSilButonActionPerformed
        // TODO add your handling code here:
        TarifSil tarifsil = new TarifSil();
        tarifsil.setVisible(true);
    }//GEN-LAST:event_TarifSilButonActionPerformed

    private void MalzemeSilButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalzemeSilButonActionPerformed
        // TODO add your handling code here:
        MalzemeSil malzemesil = new MalzemeSil();
        malzemesil.setVisible(true);
    }//GEN-LAST:event_MalzemeSilButonActionPerformed

    private void MalzemeDuzenleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalzemeDuzenleButonActionPerformed
        // TODO add your handling code here:
        MalzemeDuzenle malzemeduzenle = new MalzemeDuzenle();
        malzemeduzenle.setVisible(true);
    }//GEN-LAST:event_MalzemeDuzenleButonActionPerformed

    private void TarifDuzenleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarifDuzenleButonActionPerformed
        // TODO add your handling code here:
        TarifDuzenle tarifduzenle = new TarifDuzenle();
        tarifduzenle.setVisible(true);
    }//GEN-LAST:event_TarifDuzenleButonActionPerformed

    private void TarifAratButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarifAratButonActionPerformed
        // TODO add your handling code here:
        TarifArat tarifarat = new TarifArat();
        tarifarat.setVisible(true);
    }//GEN-LAST:event_TarifAratButonActionPerformed

    private void MalzemeAratButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalzemeAratButonActionPerformed
        // TODO add your handling code here:
        MalzemeArat malzemearat = new MalzemeArat();
        malzemearat.setVisible(true);
    }//GEN-LAST:event_MalzemeAratButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GeriDonButon;
    private javax.swing.JButton MalzemeAratButon;
    private javax.swing.JButton MalzemeDuzenleButon;
    private javax.swing.JButton MalzemeEkle;
    private javax.swing.JButton MalzemeSilButon;
    private javax.swing.JButton TarifAratButon;
    private javax.swing.JButton TarifDuzenleButon;
    private javax.swing.JButton TarifEkle;
    private javax.swing.JButton TarifSilButon;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
