/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ilhan
 */
public class TarifArat extends javax.swing.JFrame {

    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rs;
    /**
     * Creates new form TarifArat
     */
    public TarifArat() {
        initComponents();
        dbConnect();
        tarifleriGetir();
    }

    private void dbConnect() {
        try {
            String url = "jdbc:mysql://localhost:3306/jdbcdemo";
            String user = "root";
            String password = "YOUR_PASSWORD";
            conn = DriverManager.getConnection(url, user, password);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Veritabanına bağlanılamadı: " + e.getMessage());
        }
    }
    
    
    private void tarifleriGetir() {
        DefaultTableModel model = (DefaultTableModel) tariftablo.getModel();
        model.setRowCount(0); 

        try {
            String query = "SELECT * FROM tarifler";
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();

            while (rs.next()) {
                Object[] row = { 
                    rs.getInt("tarifid"), 
                    rs.getString("tarifadi"), 
                    rs.getString("kategori"), 
                    rs.getString("hazirlamasuresi"), 
                    rs.getString("talimatlar")
                };
                model.addRow(row);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Tarifler getirilemedi: " + e.getMessage());
        }
    }
    
    private void tarifleriFiltrele(String aramaTerimi) {
        DefaultTableModel model = (DefaultTableModel) tariftablo.getModel();
        model.setRowCount(0); // Tabloyu sıfırla

        try {
            String query = "SELECT * FROM tarifler WHERE tarifadi LIKE ? OR kategori LIKE ? OR hazirlamasuresi LIKE ? OR talimatlar LIKE ?";
            pst = conn.prepareStatement(query);
            pst.setString(1, "%" + aramaTerimi + "%");
            pst.setString(2, "%" + aramaTerimi + "%");
            pst.setString(3, "%" + aramaTerimi + "%");
            pst.setString(4, "%" + aramaTerimi + "%");
            
            rs = pst.executeQuery();

            while (rs.next()) {
                Object[] row = { 
                    rs.getInt("tarifid"), 
                    rs.getString("tarifadi"), 
                    rs.getString("kategori"), 
                    rs.getString("hazirlamasuresi"), 
                    rs.getString("talimatlar")
                };
                model.addRow(row);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Tarifler filtrelenemedi: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tariftablo = new javax.swing.JTable();
        geridonbuton = new javax.swing.JButton();
        arabuton = new javax.swing.JButton();
        aramatext = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tariftablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarif ID", "Tarif Adı", "Kategori", "Hazırlama Süresi", "Talimatlar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tariftablo.setColumnSelectionAllowed(true);
        tariftablo.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(tariftablo);
        tariftablo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        geridonbuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        geridonbuton.setText("Geri Dön");
        geridonbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geridonbutonActionPerformed(evt);
            }
        });

        arabuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        arabuton.setText("Ara");
        arabuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(arabuton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(geridonbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(aramatext, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(aramatext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geridonbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arabuton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arabutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabutonActionPerformed
        // TODO add your handling code here:
        String aramaterimi = aramatext.getText();
        tarifleriFiltrele(aramaterimi);
    }//GEN-LAST:event_arabutonActionPerformed

    private void geridonbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geridonbutonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_geridonbutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarifArat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarifArat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarifArat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarifArat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarifArat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arabuton;
    private javax.swing.JTextField aramatext;
    private javax.swing.JButton geridonbuton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tariftablo;
    // End of variables declaration//GEN-END:variables
}
