/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ilhan
 */
public class TarifOnerisi extends javax.swing.JFrame {

    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rs;

    /**
     * Creates new form TarifOnerisi
     */
    public TarifOnerisi() {
        initComponents();
        dbConnect();
    }

    private void dbConnect() {
        try {
            String url = "jdbc:mysql://localhost:3306/jdbcdemo";
            String user = "root";
            String password = "YOUR_PASSWORD";
            conn = DriverManager.getConnection(url, user, password);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Veritabanına bağlanılamadı: " + e.getMessage());
        }
    }

    private void tarifleriGetir() {
        DefaultTableModel model = (DefaultTableModel) oneritablo.getModel();
        model.setRowCount(0);
        String tarifQuery = "SELECT t.tarifid, t.tarifadi, t.kategori, t.hazirlamasuresi, t.talimatlar FROM tarifler t;";
        try {
            Statement tarifStatement = conn.createStatement();
            ResultSet tarifResultSet = tarifStatement.executeQuery(tarifQuery);

            while (tarifResultSet.next()) {
                int tarifid = tarifResultSet.getInt("tarifid");
                String tarifadi = tarifResultSet.getString("tarifadi");
                String kategori = tarifResultSet.getString("kategori");
                String hazirlanmasuresi = tarifResultSet.getString("hazirlamasuresi");
                String talimatlar = tarifResultSet.getString("talimatlar");

                String malzemeQuery = "SELECT m.malzemeadi, m.toplammiktar, m.malzemebirim, tm.miktar, m.birimfiyat "
                        + "FROM tarifmalzeme1 tm "
                        + "JOIN malzemeler m ON tm.malzemeid = m.malzemeid "
                        + "WHERE tm.tarifid = " + tarifid + ";";
                Statement malzemeStatement = conn.createStatement();
                ResultSet malzemeResultSet = malzemeStatement.executeQuery(malzemeQuery);
                int rowIndex = 0;

                while (malzemeResultSet.next()) {
                    String malzemeadi = malzemeResultSet.getString("malzemeadi");
                    int toplamMiktar = malzemeResultSet.getInt("toplammiktar");
                    int miktar = malzemeResultSet.getInt("miktar");
                    int birimfiyat = malzemeResultSet.getInt("birimfiyat");
                    String malzemeBirim = malzemeResultSet.getString("malzemebirim");

                    double oran;
                    String malzemeOranı;
                    if (miktar == 0) {
                        oran = 0;
                    } else {
                        oran = (double) toplamMiktar / miktar * 100; 
                        if (oran > 100) {
                            oran = 100;
                        }
                    }
                    malzemeOranı = String.format("%.2f%%", oran); 
                    String miktarVeBirim = miktar + " " + malzemeBirim;
                    // Tabloya ekleme
                    model.addRow(new Object[]{
                        tarifid,
                        tarifadi,
                        kategori,
                        hazirlanmasuresi,
                        talimatlar,
                        malzemeadi,
                        miktarVeBirim,
                        malzemeOranı, 
                        String.valueOf(birimfiyat)
                    });

                    rowIndex = model.getRowCount() - 1; 
                    if (oran < 100) {
                        // Kırmızı renkte göster
                        oneritablo.setValueAt("<html><font color='red'>" + malzemeOranı + "</font></html>", rowIndex, 7);
                        oneritablo.setValueAt(String.valueOf(birimfiyat), rowIndex, 8);
                    } else if (oran == 100) {
                        // Yeşil renkte göster
                        oneritablo.setValueAt("<html><font color='green'>" + malzemeOranı + "</font></html>", rowIndex, 7);
                        oneritablo.setValueAt("0", rowIndex, 8); 
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        oneritablo = new javax.swing.JTable();
        geributon = new javax.swing.JButton();
        getirbuton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        oneritablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarif ID", "Tarif Adı", "Kategori", "Hazırlama Süresi", "Talimatlar", "Malzemeler", "Miktar", "Malzeme Oranı", "Maliyet"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        oneritablo.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(oneritablo);

        geributon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        geributon.setText("Geri Dön");
        geributon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geributonActionPerformed(evt);
            }
        });

        getirbuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getirbuton.setText("Getir");
        getirbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getirbutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(getirbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(geributon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geributon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getirbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void geributonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geributonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_geributonActionPerformed

    private void getirbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getirbutonActionPerformed
        // TODO add your handling code here:
        tarifleriGetir();
    }//GEN-LAST:event_getirbutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarifOnerisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarifOnerisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarifOnerisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarifOnerisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarifOnerisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geributon;
    private javax.swing.JButton getirbuton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable oneritablo;
    // End of variables declaration//GEN-END:variables
}
