
import java.sql.*;
import javax.swing.*;

public class TarifEkle extends javax.swing.JFrame {

    /**
     * Creates new form TarifEkle
     */
    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rs;

    public TarifEkle() {
        initComponents();
        dbConnect();
        tarifleriYukle();
        setDefaultCloseOperation(TarifEkle.DISPOSE_ON_CLOSE);
    }

    private void dbConnect() {
        try {
            String url = "jdbc:mysql://localhost:3306/jdbcdemo";
            String user = "root";
            String password = "YOUR_PASSWORD";
            conn = DriverManager.getConnection(url, user, password);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Veritabanına bağlanılamadı: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eklebuton = new javax.swing.JButton();
        vazgecbuton = new javax.swing.JButton();
        tarifidtext = new javax.swing.JTextField();
        tarifaditext = new javax.swing.JTextField();
        kategoritext = new javax.swing.JTextField();
        hazirlanmasuresitext = new javax.swing.JTextField();
        talimatlartext = new javax.swing.JTextField();
        cmbmalzeme1 = new javax.swing.JComboBox<>();
        cmbmalzeme2 = new javax.swing.JComboBox<>();
        malzemelertext = new javax.swing.JLabel();
        malzemeeklebuton = new javax.swing.JButton();
        malzeme1 = new javax.swing.JTextField();
        malzeme2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tarif ID");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tarif Adı");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Kategori");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hazırlanma Süresi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Talimatlar");

        eklebuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eklebuton.setText("Ekle");
        eklebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eklebutonActionPerformed(evt);
            }
        });

        vazgecbuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vazgecbuton.setText("Vazgeç");
        vazgecbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vazgecbutonActionPerformed(evt);
            }
        });

        tarifidtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifidtextActionPerformed(evt);
            }
        });

        cmbmalzeme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmalzeme1ActionPerformed(evt);
            }
        });

        cmbmalzeme2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmalzeme2ActionPerformed(evt);
            }
        });

        malzemelertext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        malzemelertext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        malzemelertext.setText("Malzemeler");

        malzemeeklebuton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        malzemeeklebuton.setText("Yeni Malzeme Ekle");
        malzemeeklebuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malzemeeklebutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(eklebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(malzemeeklebuton)
                .addGap(30, 30, 30)
                .addComponent(vazgecbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbmalzeme1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbmalzeme2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tarifaditext, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tarifidtext, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(kategoritext, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hazirlanmasuresitext, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(talimatlartext, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(malzeme1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(malzeme2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(malzemelertext, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tarifidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tarifaditext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kategoritext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hazirlanmasuresitext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(talimatlartext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(malzemelertext, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbmalzeme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(malzeme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbmalzeme2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(malzeme2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eklebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vazgecbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(malzemeeklebuton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eklebutonActionPerformed
        String queryInsert = "INSERT INTO tarifler (tarifid, tarifadi, kategori, hazirlamasuresi, talimatlar) VALUES (?, ?, ?, ?, ?)";
    String queryUpdate = "UPDATE tarifler SET tarifadi=?, kategori=?, hazirlamasuresi=?, talimatlar=? WHERE tarifid=?";
    String queryTarifMalzeme = "INSERT INTO tarifmalzeme1 (tarifid, malzemeid, miktar) VALUES (?, ?, ?)";
    String queryGetMalzemeId = "SELECT malzemeid FROM malzemeler WHERE malzemeadi = ?";

    int id = Integer.parseInt(tarifidtext.getText());
    String ad = tarifaditext.getText();
    String kategori = kategoritext.getText();
    String hazirlanmasuresi = hazirlanmasuresitext.getText();
    String talimatlar = talimatlartext.getText();

    String malzemeAdi1 = cmbmalzeme1.getSelectedItem().toString();
    String malzemeAdi2 = cmbmalzeme2.getSelectedItem().toString();
    int miktar1 = Integer.parseInt(malzeme1.getText());
    int miktar2 = Integer.parseInt(malzeme2.getText());

    try {
        String checkQuery = "SELECT COUNT(*) FROM tarifler WHERE tarifid = ?";
        PreparedStatement checkStm = conn.prepareStatement(checkQuery);
        checkStm.setInt(1, id);
        ResultSet rs = checkStm.executeQuery();
        
        if (rs.next() && rs.getInt(1) > 0) { 
            PreparedStatement updateStm = conn.prepareStatement(queryUpdate);
            updateStm.setString(1, ad);
            updateStm.setString(2, kategori);
            updateStm.setString(3, hazirlanmasuresi);
            updateStm.setString(4, talimatlar);
            updateStm.setInt(5, id);
            updateStm.executeUpdate();
            JOptionPane.showMessageDialog(this, "Tarif güncellendi.");
        } else { 
            PreparedStatement insertStm = conn.prepareStatement(queryInsert);
            insertStm.setInt(1, id);
            insertStm.setString(2, ad);
            insertStm.setString(3, kategori);
            insertStm.setString(4, hazirlanmasuresi);
            insertStm.setString(5, talimatlar);
            insertStm.execute();
            JOptionPane.showMessageDialog(this, "Yeni tarif eklendi.");
        }

        PreparedStatement getMalzemeIdStm1 = conn.prepareStatement(queryGetMalzemeId);
        getMalzemeIdStm1.setString(1, malzemeAdi1);
        ResultSet rs1 = getMalzemeIdStm1.executeQuery();
        if (rs1.next()) {
            int malzemeid1 = rs1.getInt("malzemeid");
            PreparedStatement tarifMalzemeStm1 = conn.prepareStatement(queryTarifMalzeme);
            tarifMalzemeStm1.setInt(1, id);
            tarifMalzemeStm1.setInt(2, malzemeid1);
            tarifMalzemeStm1.setInt(3, miktar1);
            tarifMalzemeStm1.executeUpdate();
        }

        PreparedStatement getMalzemeIdStm2 = conn.prepareStatement(queryGetMalzemeId);
        getMalzemeIdStm2.setString(1, malzemeAdi2);
        ResultSet rs2 = getMalzemeIdStm2.executeQuery();
        if (rs2.next()) {
            int malzemeid2 = rs2.getInt("malzemeid");
            PreparedStatement tarifMalzemeStm2 = conn.prepareStatement(queryTarifMalzeme);
            tarifMalzemeStm2.setInt(1, id);
            tarifMalzemeStm2.setInt(2, malzemeid2);
            tarifMalzemeStm2.setInt(3, miktar2);
            tarifMalzemeStm2.executeUpdate();
        }

        tarifidtext.setText(null);
        tarifaditext.setText(null);
        kategoritext.setText(null);
        hazirlanmasuresitext.setText(null);
        talimatlartext.setText(null);
        malzeme1.setText(null);
        malzeme2.setText(null);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Hata: " + e.getMessage());
    }

    }//GEN-LAST:event_eklebutonActionPerformed

    private void tarifidtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifidtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifidtextActionPerformed

    private void vazgecbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vazgecbutonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_vazgecbutonActionPerformed

    private void cmbmalzeme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmalzeme1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmalzeme1ActionPerformed

    private void cmbmalzeme2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmalzeme2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmalzeme2ActionPerformed

    private void malzemeeklebutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malzemeeklebutonActionPerformed
        // TODO add your handling code here:
        MalzemeEkle malzemeekle = new MalzemeEkle();
        malzemeekle.setVisible(true);
    }//GEN-LAST:event_malzemeeklebutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarifEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarifEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarifEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarifEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarifEkle().setVisible(true);
            }
        });
    }

    private void tarifleriYukle() {
        DefaultComboBoxModel<String> model1 = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>();

        try {
            String query = "SELECT malzemeadi FROM malzemeler";
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();

            while (rs.next()) {
                String malzemeAdi = rs.getString("malzemeadi");
                model1.addElement(malzemeAdi);
                model2.addElement(malzemeAdi);
            }

            cmbmalzeme1.setModel(model1);
            cmbmalzeme2.setModel(model2);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Tarifler yüklenemedi: " + e.getMessage());
        }

        cmbmalzeme1.setSelectedIndex(-1); 
        cmbmalzeme2.setSelectedIndex(-1); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbmalzeme1;
    private javax.swing.JComboBox<String> cmbmalzeme2;
    private javax.swing.JButton eklebuton;
    private javax.swing.JTextField hazirlanmasuresitext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField kategoritext;
    private javax.swing.JTextField malzeme1;
    private javax.swing.JTextField malzeme2;
    private javax.swing.JButton malzemeeklebuton;
    private javax.swing.JLabel malzemelertext;
    private javax.swing.JTextField talimatlartext;
    private javax.swing.JTextField tarifaditext;
    private javax.swing.JTextField tarifidtext;
    private javax.swing.JButton vazgecbuton;
    // End of variables declaration//GEN-END:variables
}
